kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/ch1aki/c2go

steps:
- name: fetch
  image: docker:git
  commands:
    - git fetch --tags

- name: test
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
  - go get
  - go test

- name: build
  image: golang
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes:
    - name: deps
      path: /go
  commands:
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag

volumes:
  - name: deps
    temp: {}